### ISSUE TITLE
Ubuntu 17.10 - 启动失败 (~/.Xauthority)

### ISSUE THREAD

**Issue by lambdald** [yomun/youdaodict_5.5#1]
raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/home/lidong/.Xauthority'

自己建个就好了
touch ~/.Xauthority

**Comment by yomun** [comment]
我也在用 Ubuntu 17.10,
但不需要 ~/.Xauthority

反而, 在 Fedora 中需要.
