### ISSUE TITLE
Ubuntu 18.04 - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Kcaii** [yomun/youdaodict_5.5#2]
*Ubuntu Version*: 18.04
*Kernel*: 4.15.0-13-generic
*Shell*: Bash 4.4.18

```
Youdao Dict Unique Services is started...
Segmentation fault (core dumped)
```

**Comment by yomun** [comment]
Ubuntu 18.04 正式版要在4月26日才推出.

**Comment by yomun** [comment]
VirtualBox 上 Ubuntu 18.04 BETA 2 用有道词典
除了安装依赖软件包, 还需要..

1) 启动 3D 加速 (VirtualBox - Settings - Display - Screen - Acceleration - Enable 3D Acceleration)

2) 显卡驱动安装

- GUI 安装 (GNOME 左下角 Show Applications - 打开 Software & Updates - Additional Drivers)
--> InnoTek Systemberatung GmbH: VirtualBox Graphics Adapter
-----> Using x86 virtualization solution-X11 guest utilities from virtualbox-guest-x11-**hwe**(proprietary)
--> InnoTek Systemberatung GmbH: VirtualBox Guest Service
-----> Using x86 virtualization solution-guest addition module source for dkms from virtualbox-guest-dkms-**hwe**(proprietary)

- 命令安装 (打开 terminal)
--> $ sudo apt install virtualbox-guest-x11-hwe virtualbox-guest-dkms-hwe virtualbox-guest-utils-hwe

如果你不是在 VirtualBox 上安装 Ubuntu, 那你就要确认是否已安装上显卡驱动了

**Comment by Kcaii** [comment]
感谢回答，我用的是双系统，不是VirtualBox。最近`sudo apt-get update && sudo apt-get upgrade` 之后问题得到解决，可能是非正式版系统的bug。

**Comment by yomun** [comment]
- 考虑到系统安全, 系统经常更新是必要的
- Ubuntu 如果你没改配置, 已可以自动每天检查更新
