### ISSUE TITLE
Ubuntu 18.04 - ImportError: cannot import name 'QApplication'

### ISSUE THREAD

**Issue by wangzhenyu1993** [yomun/youdaodict_5.5#5]
运行有道词典后，提示，cannot import name 'QApplication'？

**Comment by wangzhenyu1993** [comment]
完整报错
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 31, in <module>
    from PyQt5.Qt import QApplication
ImportError: cannot import name 'QApplication'

**Comment by yomun** [comment]
- 确保不要用 pip3 安装 PyQt5, 如有, 卸载之
- 确认所有的依赖软件包都安装了
```
$ su

$ apt install python3-pyqt5 python3-pyqt5.qtmultimedia python3-pyqt5.qtquick
$ apt install python3-pyqt5.qtwebkit

QApplication 模块就包含在 python3-pyqt5.qtwebkit 上
```

安装说明已讲得很清楚了..
https://github.com/yomun/youdaodict_5.5

**Comment by wangzhenyu1993** [comment]
你好，都通过ａｐｔ安装了但是还是报错　同样的错误，并且是５．１０．１版本的ｑｔ库

**Comment by wangzhenyu1993** [comment]
并且没有通过ｐｉｐ３安装

**Comment by yomun** [comment]
- 指定所要运行的 Python 3 依赖软件包路径
$ sudo gedit /usr/share/applications/youdao-dict.desktop
修改 Exec=**env PYTHONPATH=/usr/lib/python3/dist-packages** youdao-dict %f

- 检查 sys.path 值 (如果 '/usr/lib/python3/dist-packages' 是列在最后, 以上可以跳过)
```
~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
```
- 参考这个
https://github.com/yomun/youdaodict_5.5/issues/4

**Comment by wangzhenyu1993** [comment]
sys.path
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']　我的记录是这样的．

**Comment by yomun** [comment]
- 指定所要运行的 Python 3 依赖软件包路径
```
通过图标运行
-------------
$ sudo gedit /usr/share/applications/youdao-dict.desktop
修改成 Exec=env PYTHONPATH=/usr/lib/python3/dist-packages youdao-dict %f
重启, 点击图标

或

通过 terminal 直接运行
-----------------------
$ env PYTHONPATH=/usr/lib/python3/dist-packages youdao-dict %f
```

- 确保以下文件都存在 (**/usr/lib/python3/dist-packages**/PyQt5)
如果缺了, 就是说安装少了软件包
python3-pyqt5 
python3-pyqt5.qtmultimedia 
python3-pyqt5.qtquick 
python3-pyqt5.qtwebkit
```
$ cd /usr/lib/python3/dist-packages/PyQt5
$ ls

__init__.py
__pycache__
QtCore.cpython-36m-x86_64-linux-gnu.so
QtCore.pyi
Qt.cpython-36m-x86_64-linux-gnu.so
QtDBus.cpython-36m-x86_64-linux-gnu.so
QtDBus.pyi
QtDesigner.cpython-36m-x86_64-linux-gnu.so
QtDesigner.pyi
QtGui.cpython-36m-x86_64-linux-gnu.so
QtGui.pyi
QtHelp.cpython-36m-x86_64-linux-gnu.so
QtHelp.pyi
QtMultimedia.cpython-36m-x86_64-linux-gnu.so
QtMultimedia.pyi
QtMultimediaWidgets.cpython-36m-x86_64-linux-gnu.so
QtMultimediaWidgets.pyi
QtNetwork.cpython-36m-x86_64-linux-gnu.so
QtNetwork.pyi
QtPrintSupport.cpython-36m-x86_64-linux-gnu.so
QtPrintSupport.pyi
QtQml.cpython-36m-x86_64-linux-gnu.so
QtQml.pyi
QtQuick.cpython-36m-x86_64-linux-gnu.so
QtQuick.pyi
QtQuickWidgets.cpython-36m-x86_64-linux-gnu.so
QtQuickWidgets.pyi
QtTest.cpython-36m-x86_64-linux-gnu.so
QtTest.pyi
QtWebKit.cpython-36m-x86_64-linux-gnu.so
QtWebKit.pyi
QtWebKitWidgets.cpython-36m-x86_64-linux-gnu.so
QtWebKitWidgets.pyi
QtWidgets.cpython-36m-x86_64-linux-gnu.so
QtWidgets.pyi
QtXml.cpython-36m-x86_64-linux-gnu.so
QtXml.pyi
uic

$ ls | wc -l
38
```

**Comment by wangzhenyu1993** [comment]
wangzhenyu@wangzhenyu:/usr/lib/python3/dist-packages/PyQt5$ ls
__init__.py
__pycache__
QtCore.cpython-36m-x86_64-linux-gnu.so
QtCore.pyi
Qt.cpython-36m-x86_64-linux-gnu.so
QtDBus.cpython-36m-x86_64-linux-gnu.so
QtDBus.pyi
QtDesigner.cpython-36m-x86_64-linux-gnu.so
QtDesigner.pyi
QtGui.cpython-36m-x86_64-linux-gnu.so
QtGui.pyi
QtHelp.cpython-36m-x86_64-linux-gnu.so
QtHelp.pyi
QtMultimedia.cpython-36m-x86_64-linux-gnu.so
QtMultimedia.pyi
QtMultimediaWidgets.cpython-36m-x86_64-linux-gnu.so
QtMultimediaWidgets.pyi
QtNetwork.cpython-36m-x86_64-linux-gnu.so
QtNetwork.pyi
QtPrintSupport.cpython-36m-x86_64-linux-gnu.so
QtPrintSupport.pyi
QtQml.cpython-36m-x86_64-linux-gnu.so
QtQml.pyi
QtQuick.cpython-36m-x86_64-linux-gnu.so
QtQuick.pyi
QtQuickWidgets.cpython-36m-x86_64-linux-gnu.so
QtQuickWidgets.pyi
QtTest.cpython-36m-x86_64-linux-gnu.so
QtTest.pyi
QtWebKit.cpython-36m-x86_64-linux-gnu.so
QtWebKit.pyi
QtWebKitWidgets.cpython-36m-x86_64-linux-gnu.so
QtWebKitWidgets.pyi
QtWidgets.cpython-36m-x86_64-linux-gnu.so
QtWidgets.pyi
QtXml.cpython-36m-x86_64-linux-gnu.so
QtXml.pyi
uic
是３8个　按你要求改了　但是提示是
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 31, in <module>
    from PyQt5.Qt import QApplication
ImportError: cannot import name 'QApplication'

**Comment by yomun** [comment]
你到底用的是哪个版本的 Ubuntu 18.04 LTS (Gnome)?
是否在官网下载?  https://www.ubuntu.com/download/desktop

还不行, 自己重新安装OS或用虚拟机.

```
$ env PYTHONPATH=/usr/lib/python3/dist-packages python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.Qt import QApplication
>>> Ctrl+D 退出

$ env PYTHONPATH=/usr/lib/python3/dist-packages youdao-dict %f
```

**Comment by wangzhenyu1993** [comment]
wangzhenyu@wangzhenyu:~$ env PYTHONPATH=/usr/lib/python3/dist-packages python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.Qt import QApplication
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QApplication'
官网下载的ubuntu　但是无法导入这个包　我查了下　很多人说这个包已经没有这个模块ＱＡＰＰlication

**Comment by yomun** [comment]
我敢肯定与很负责任的说
```
>>> from PyQt5.Qt import QApplication
```
模块是存在的, 且可以运行

以上已测试过了. 至少在 Ubuntu 18.04 版本(Python 3.6) 是没问题的.

**Comment by yomun** [comment]
如果有 pip3 安装的 PyQt5, 卸载之.
只保留用 apt 安装的 PyQt5
