### ISSUE TITLE
Ubuntu 18.04 - ModuleNotFoundError: No module named 'Xlib'

### ISSUE THREAD

**Issue by Jayden-zdd** [yomun/youdaodict_5.5#6]
access control disabled, clients can connect from any host
Traceback (most recent call last):
  File "/usr/bin/youdao-dict", line 27, in <module>
    from dae.daeclient import DAEClient
  File "/usr/share/youdao-dict/dae/daeclient.py", line 36, in <module>
    from dae.window import Window
  File "/usr/share/youdao-dict/dae/window.py", line 30, in <module>
    from dae.shadowwindow import ShadowWindow
  File "/usr/share/youdao-dict/dae/shadowwindow.py", line 28, in <module>
    import dae.xutils as xutils
  File "/usr/share/youdao-dict/dae/xutils.py", line 23, in <module>
    import Xlib.X
ModuleNotFoundError: No module named 'Xlib'

my system is ubuntu18.04, according to your steps,there is the problem on above,how to solve it?Thank you.

**Comment by yomun** [comment]
检查你的 python3-xlib 安装包
```
$ apt search python3-xlib
Sorting... Done
Full Text Search... Done
python3-xlib/bionic,bionic,now 0.20-3 all [installed]
  interface for Python 3 to the X11 protocol
```

**Comment by Jayden-zdd** [comment]
apt install python3-dbus python3-lxml python3-pil python3-requests python3-xdg python3-xlib
首先这里已经安装
其次输入 apt search python3-xlib，结果如下：
正在排序... 完成
全文搜索... 完成  
python3-xlib/bionic,bionic,now 0.20-3 all [已安装]
  interface for Python 3 to the X11 protocol
最后安装依赖包的时候apt install libqt5multimedia5-plugins fonts-wqy-microhei（我是ubuntu18.04）
然后运行xhost + && youdao-dict还是之前的错误
access control disabled, clients can connect from any host
Traceback (most recent call last):
File "/usr/bin/youdao-dict", line 27, in 
from dae.daeclient import DAEClient
File "/usr/share/youdao-dict/dae/daeclient.py", line 36, in 
from dae.window import Window
File "/usr/share/youdao-dict/dae/window.py", line 30, in 
from dae.shadowwindow import ShadowWindow
File "/usr/share/youdao-dict/dae/shadowwindow.py", line 28, in 
import dae.xutils as xutils
File "/usr/share/youdao-dict/dae/xutils.py", line 23, in 
import Xlib.X
ModuleNotFoundError: No module named 'Xlib'

**Comment by yomun** [comment]
不知你之前玩过什么, 造成 Xlib 这模块不能在 Python3 上运行
正常情况下..
```
$ python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Xlib
>>> import Xlib.X
>>>
``` 
以上两行能够运行.
如果不行的话, 建议重新安装系统.

**Comment by yomun** [comment]
最近有新的发现,
如果你用 pip3 安装了 python3-xlib, 也会出现你说的错误。
如有, 卸载之.. 
$ su
$ pip3 uninstall python3-xlib
我们只需要安装一个版本, 即用 apt 安装的

**Comment by yomun** [comment]
```
从 apt 安装了 python3-xlib, 
pip3 上应该会出现以下

$ pip3 list | grep xlib
python-xlib             0.20               

$ pip3 show python-xlib
Name: python-xlib
Version: 0.20
Summary: Python X Library
Home-page: https://github.com/python-xlib/python-xlib
Author: Peter Liljenberg
Author-email: petli@ctrl-c.liu.se
License: LGPLv2+
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by:
```
