### ISSUE TITLE
Ubuntu 18.10 - 进程 “python3 /usr/bin/youdao-dict”内存占用过多

### ISSUE THREAD

**Issue by iwanderer** [yomun/youdaodict_5.5#7]
从任务管理器可以看到，不时CPU占用过多，并且内存达到2.2G。

**Comment by iwanderer** [comment]
刚才一看，已经占用了5.1G内存。。。

**Comment by iwanderer** [comment]
刚启动时，内存占用90M+，半小时后再看，140M+，大概以每分钟2M的速度逐渐递增

**Comment by yomun** [comment]
建议利用 cron 定期关掉再重启.
https://raw.githubusercontent.com/yomun/youdaodict_5.5/master/youdao-restart.sh
